version: 2
updates:
- package-ecosystem: nuget
  directory: "/TaskRouter.Web.Tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: NUnit
    versions:
    - 3.13.0
    - 3.13.1
  - dependency-name: Twilio
    versions:
    - 5.53.1
    - 5.54.0
    - 5.55.0
    - 5.56.0
    - 5.57.0
    - 5.58.0
  - dependency-name: Microsoft.Net.Compilers
    versions:
    - 3.8.0
  - dependency-name: Moq
    versions:
    - 4.16.0
- package-ecosystem: nuget
  directory: "/TaskRouter.Web"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: SQLite.CodeFirst
    versions:
    - 1.6.1.31
  - dependency-name: JWT
    versions:
    - 8.1.2
